# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90ddea6161f58066ec7d0a45041c1c25b239461dbcf2dbc766271132b004bb2abd468f7e22422b63c12e62ac52cfa71fd9fdfae11c52dfea8260ac2a3d219b0b

test:
  secret_key_base: 44143e172899db1fb5f91db647bc8dec1a2a9452e6710e764fe8b5cc3e763b3b1e23dea8c608ba0a9e7d0f3e22fc9008eb7c79bf3c4565d30bb70b4b0a5c3096

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
